# <center> Perceptron Algorithm 

In [108]:
import numpy as np
import pandas as pd

### Load the data

In [109]:
train_data = pd.read_csv("../data/perceptron_algorithm_data.csv", header = None)
train_data.columns = ["p", "q", "correctly_classified"]
train_data.head()

p         q  correctly_classified
0  0.78051 -0.063669                     1
1  0.28774  0.291390                     1
2  0.40714  0.178780                     1
3  0.29230  0.421700                     1
4  0.50922  0.352560                     1

In [57]:
train_data[train_data["correctly_classified"]==0]

p        q  correctly_classified  \
50  0.55330  1.00000                     0   
51  0.44274  0.59205                     0   
52  0.85176  0.66120                     0   
53  0.60436  0.86605                     0   
54  0.68243  0.48301                     0   
55  1.00000  0.76815                     0   
56  0.72989  0.81070                     0   
57  0.67377  0.77975                     0   
58  0.78761  0.58177                     0   
59  0.71442  0.76680                     0   
60  0.49379  0.54226                     0   
61  0.78974  0.74233                     0   
62  0.67905  0.60921                     0   
63  0.66420  0.72519                     0   
64  0.79396  0.56789                     0   
65  0.70758  0.76022                     0   
66  0.59421  0.61857                     0   
67  0.49364  0.56224                     0   
68  0.77707  0.35025                     0   
69  0.79785  0.76921                     0   
70  0.70876  0.96764                     0   
71  0.69176  0.60865                     0   
72  0.66408  0.92075                     0   
73  0.65973  0.66666                     0   
74  0.64574  0.56845                     0   
75  0.89639  0.70850                     0   
76  0.85476  0.63167                     0   
77  0.62091  0.80424                     0   
78  0.79057  0.56108                     0   
79  0.58935  0.71582                     0   
80  0.56846  0.74060                     0   
81  0.65912  0.71548                     0   
82  0.70938  0.74041                     0   
83  0.59154  0.62927                     0   
84  0.45829  0.46410                     0   
85  0.79982  0.74847                     0   
86  0.60974  0.54757                     0   
87  0.68127  0.86985                     0   
88  0.76694  0.64736                     0   
89  0.69048  0.83058                     0   
90  0.68122  0.96541                     0   
91  0.73229  0.64245                     0   
92  0.76145  0.60138                     0   
93  0.58985  0.86955                     0   
94  0.73145  0.74516                     0   
95  0.77029  0.70140                     0   
96  0.73156  0.71782                     0   
97  0.44556  0.57991                     0   
98  0.85275  0.85987                     0   
99  0.51912  0.62359                     0   

                                            X  
50                              (0.5533, 1.0)  
51             (0.44273999999999997, 0.59205)  
52               (0.8517600000000001, 0.6612)  
53                         (0.60436, 0.86605)  
54             (0.68243, 0.48301000000000005)  
55                             (1.0, 0.76815)  
56               (0.7298899999999999, 0.8107)  
57                         (0.67377, 0.77975)  
58                         (0.78761, 0.58177)  
59               (0.7144199999999999, 0.7668)  
60  (0.49378999999999995, 0.5422600000000001)  
61                         (0.78974, 0.74233)  
62                         (0.67905, 0.60921)  
63                          (0.6642, 0.72519)  
64                         (0.79396, 0.56789)  
65                         (0.70758, 0.76022)  
66                         (0.59421, 0.61857)  
67             (0.49363999999999997, 0.56224)  
68              (0.7770699999999999, 0.35025)  
69              (0.79785, 0.7692100000000001)  
70              (0.7087600000000001, 0.96764)  
71                         (0.69176, 0.60865)  
72                         (0.66408, 0.92075)  
73                         (0.65973, 0.66666)  
74                         (0.64574, 0.56845)  
75               (0.8963899999999999, 0.7085)  
76              (0.8547600000000001, 0.63167)  
77              (0.6209100000000001, 0.80424)  
78                         (0.79057, 0.56108)  
79                         (0.58935, 0.71582)  
80               (0.5684600000000001, 0.7406)  
81              (0.6591199999999999, 0.71548)  
82                         (0.70938, 0.74041)  
83                         (0.5

In [39]:
train_data["X"] = tuple(zip(train_data["p"], train_data["q"]))

In [41]:
train_data

p         q  correctly_classified                             X
0   0.78051 -0.063669                     1          (0.78051, -0.063669)
1   0.28774  0.291390                     1            (0.28774, 0.29139)
2   0.40714  0.178780                     1            (0.40714, 0.17878)
3   0.29230  0.421700                     1              (0.2923, 0.4217)
4   0.50922  0.352560                     1            (0.50922, 0.35256)
..      ...       ...                   ...                           ...
95  0.77029  0.701400                     0  (0.7702899999999999, 0.7014)
96  0.73156  0.717820                     0            (0.73156, 0.71782)
97  0.44556  0.579910                     0            (0.44556, 0.57991)
98  0.85275  0.859870                     0            (0.85275, 0.85987)
99  0.51912  0.623590                     0            (0.51912, 0.62359)

[100 rows x 4 columns]

### Setting the random seed, feel free to change it and see different solutions

In [29]:
np.random.seed(42)

### Define step and prediction functions

In [30]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0


def prediction(X, W, b):
    return stepFunction((np.matmul(X, W) + b)[0])

In [96]:
X = np.array([(3,9), (2,2)])

In [97]:
W = [[1,2], [3,3]]

In [98]:
X = np.array([(3,9), (2,2)])
W = np.array([(1,2), (3,3)]).transpose()

In [99]:
X

array([[3, 9],
       [2, 2]])

In [100]:
W

array([[1, 3],
       [2, 3]])

In [101]:
np.matmul(X,W)

array([[21, 36],
       [ 6, 12]])

### Define the perceptronStep function to implement the Perceptron Trick

In [31]:
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate=0.01):
    for x, y_val, w, b in zip(X, y, W, b):
        if y_val == 0:
            w[0] += learn_rate*x[0]
            w[1] += learn_rate*x[1]
            b_val += learn_rate
        else:
            w[0] -= learn_rate*x[0]
            w[1] -= learn_rate*x[1]
            b_val -= learn_rate
    return W, b

In [32]:
perceptronStep([], [0, 1], W, b, learn_rate=0.01):

SyntaxError: invalid syntax (<ipython-input-32-65728ff619e4>, line 1)

### This function runs the perceptron algorithm repeatedly on the dataset, and returns a few of the boundary lines obtained in the iterations, for plotting purposes.

In [33]:
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate=0.01, num_epochs=25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2, 1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0] / W[1], -b / W[1]))
    return boundary_lines